### PR TITLE
fix: add type of id to hasMember

### PR DESCRIPTION
**Pull request by satra**
hasMember needs type augmentation to identify all the dandiassets as uris.

### CODE REVIEW

**Comment by yarikoptic** [comment]
could some test be added (or just changed) to demonstrate/cover this case?

**Comment by satra** [comment]
we haven't really added any of the jsonld stuff beyond just decorating things. a proper test for this would be that we are generating an appropriate quad. before i bring the whole pyld/shacl world into this, i think this is ok for now.

but i pushed a silly test.

**Comment by satra** [comment]
@dchiquito - i'll wait for these tests and then this should trigger a release.

**Comment by satra** [comment]
@jwodder i'll merge this despite the zarr test failures, since https://github.com/dandi/dandi-cli/pull/933 needs this new version of dandischema library to fix the test.

**Pull request merged**
