### PR TITLE
release.yml: Use DANDI_GITHUB_TOKEN to push to repo

### LINKED ISSUE #43: add branch protection rules and update auto config
`auto` does work with branch protection rules, it requires two things:

1. see here for the repo setup: https://github.com/neuronets/nobrainer/blob/master/.github/workflows/release.yml#L20
2. requires a personal access token instead of GITHUB_TOKEN

the one thing that i have not implemented in the nobrainer  yet is that the twine upload should only work if auto creates a new release, but not otherwise. i'll be looking into that soon.

### PR DESCRIPTION
**Pull request by jwodder**
Closes #43.

### CODE REVIEW

**Comment by satra** [comment]
i think this may also need the git checkout and git ref update that was in the linked yaml

**Comment by satra** [comment]
or we can test this by giving it a release + patch label first.

**Comment by jwodder** [comment]
@satra Do you mean the `git fetch --unshallow --tags`?  That's equivalent to passing `with: {fetch-depth: 0}` to the checkout action.

**Comment by satra** [comment]
the section after that.

**Comment by jwodder** [comment]
@satra The `git config --local --unset` should be taken care of by specifying `token: ${{ secrets.DANDI_GITHUB_TOKEN }}` when checking out.

**Comment by satra** [comment]
ok let's check it out. i added the release + patch labels. merging now.

**Comment by jwodder** [comment]
@satra It failed because the 0.2.9 tag already exists from the last failed release.

**Comment by satra** [comment]
just deleted it and triggering a new release.

**Pull request merged**
