### PR TITLE
fix: remove readOnly from constants

### PR DESCRIPTION
**Pull request by satra**
a fix to make us compatible with the vjsf component for meditor.

### CODE REVIEW

**Comment by satra** [comment]
@yarikoptic - this does not change the models and only the schema. should we overwrite the schema or increase schema as well? the only thing this impacts is the meditor component.

**Comment by satra** [comment]
bumped schema version anyway.

**Comment by waxlamp** [comment]
> bumped schema version anyway.

I believe the patch level bump was appropriate and required in this case.

**Review by yarikoptic — APPROVED** [review]
I am glad to have similar minded zealots of versioning on the team @waxlamp ! ;-)

In general approve, but shouldn't we have just patch label on library then, instead of minor?

**Comment by satra** [comment]
yes, should be patch.

**Pull request merged**
