### PR TITLE
Specify part generator to DandiETag class

### PR DESCRIPTION
**Pull request by AlmightyYakob**
This is another small change that accompanies #116.

If this is approved I'd like to add the `release` label to this so that changes in both this and #116 are available.

### CODE REVIEW

**Review by jwodder — APPROVED** [review]

**Comment by jwodder** [comment]
@AlmightyYakob Ping.

**Comment by AlmightyYakob** [comment]
I can't find anywhere in the current API codebase that this is used. I know it _was_ used at some point, but that code has now either been refactored or removed entirely.

**Comment by jwodder** [comment]
@AlmightyYakob So, would it be OK if this PR was reverted?

**Comment by AlmightyYakob** [comment]
> @AlmightyYakob So, would it be OK if this PR was reverted?

At least from the API side I think it's safe to revert, but I haven't checked any other repos. Although I'd be surprised if it was being made use of anywhere else.

**Comment by jwodder** [comment]
@AlmightyYakob I think for now I'll keep this code, but I've annotated it such that `part_gen` needs to be either `PartGenerator` or a subclass thereof, not just a class that works the same way.

**Comment by AlmightyYakob** [comment]
> @AlmightyYakob I think for now I'll keep this code, but I've annotated it such that `part_gen` needs to be either `PartGenerator` or a subclass thereof, not just a class that works the same way.

That seems perfectly reasonable to me.

**Pull request merged**
