### PR TITLE
TEMP: me is changing the schema without version boost - let's see what happens

### PR DESCRIPTION
**Pull request by yarikoptic**
prediction:
- nothing until I add 'release' label

edit: damn -- forgot that it is a bad example since that particular change iirc is guarded in the tests--- will come up with another one later

### CODE REVIEW

**Comment by yarikoptic** [comment]
@jwodder please take over this PR or its replacement in testing the setup (without a release) on properly reacting to schema mods and labels changes

**Comment by jwodder** [comment]
Added a field; result: normal tests pass, schema check is skipped.

**Comment by jwodder** [comment]
`release` label added; result: schema check triggered and failed successfully.

**Comment by jwodder** [comment]
`release` label removed; result: schema check reverts to "skipped" state, and all checks pass.

**Comment by jwodder** [comment]
@yarikoptic Everything appears to be working properly.

**Comment by yarikoptic** [comment]
thank you @jwodder!

**Pull request closed without merging**
