### PR TITLE
Add dandi:dandi-zarr-checksum digest

### PR DESCRIPTION
**Pull request by dchiquito**
Add a new digest type `dandi:dandi-zarr-checksum` for representing the new zarr checksum digest.

### CODE REVIEW

**Comment by satra** [comment]
@jwodder - there appears to be a few CLI failures that seem unrelated to this change.

**Comment by jwodder** [comment]
@satra I believe those are all due to the latest release of dandi not including https://github.com/dandi/dandi-cli/pull/854.

**Comment by satra** [comment]
thank you @jwodder

**Comment by jwodder** [comment]
@satra Could this be merged & released soon?  The lack of this digest type value is one of the more concrete blockers for Zarr support in dandi-cli.

**Pull request merged**
